version: "{build}"
image: Visual Studio 2019
environment:
  global:
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
test: off
branches:
  only:
    - master
    - /^release\/.*$/
build_script:
  - ps: ./build.ps1
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
artifacts:
  - path: '**\*.nupkg'
on_success:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "**\coverage.xml"
