env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - AndroidSdkDirectory=../../android-sdk/android-sdk-macosx
dotnet: 3.1.100
branches:
  only:
    - master
    - /^release\/.*$/
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic
script:
  - ./build.sh
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "*cobertura.xml"
